# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formulario.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1374, 902)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 50, 1291, 781))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grupos = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.grupos.setMaximumSize(QtCore.QSize(400, 16777215))
        self.grupos.setObjectName("grupos")
        self.horizontalLayout_2.addWidget(self.grupos)
        self.productos = QtWidgets.QTableWidget(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.productos.sizePolicy().hasHeightForWidth())
        self.productos.setSizePolicy(sizePolicy)
        self.productos.setMinimumSize(QtCore.QSize(300, 0))
        self.productos.setMaximumSize(QtCore.QSize(1000, 800))
        self.productos.setSizeIncrement(QtCore.QSize(0, 0))
        self.productos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.productos.setAlternatingRowColors(True)
        self.productos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.productos.setColumnCount(3)
        self.productos.setObjectName("productos")
        self.productos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.productos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.productos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.productos.setHorizontalHeaderItem(2, item)
        self.productos.horizontalHeader().setDefaultSectionSize(342)
        self.productos.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.productos)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1374, 39))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.productos.cellClicked['int','int'].connect(self.statusbar.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.productos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.productos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Producto"))
        item = self.productos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Estado"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
